# Generated by Django 3.0.5 on 2020-06-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('miApp', '0005_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='facturas')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
